### ISSUE TITLE
Fix sign on ulTempLatLon and look for similar issues.

### ISSUE THREAD

**Issue by dglowe** [atac/SyntheticData#6]
In Ch10Format_1553_Nav ulTempLatLon is read as uint32_t. The lat and long values should be int32_t. Maybe a few other variables need to be changed when correction is made.

**Comment by bbaggerman** [comment]
For ulTempLatLon the data format for angles is semi-circles. That is, msb = 180 degrees, 2nd msb = 90 degrees, etc. In semi-circle format expressing angles as values from 0 to 360 degrees is exactly equivalent to expressing them as values from -180 to +180 degrees. So, the binary value for -90 degrees is exactly the same as +270 degrees, which is proper because for navigation purposes they represent the same value. An unsigned representation was chosen so that there would be less chance for the compiler to change values. For example, for negative signed values sometimes the compiler sign extends upper bits when changing variable size. Sometimes it is hard to anticipate when a compiler might promote a variable. For this reason it is entirely proper for angles expressed in semi-circles to be stored in unsigned integer variables. No code change is necessary.
